# GroupBy, Concat & Merge — Practice Notebook

This notebook goes with the **GroupBy, Concat and Merge** notes. It has extra **variation** examples on top of what's in the notes, so you can practice the same idea in a few different ways.

**Datasets used:**
- `movies.csv` — 1629 Bollywood movies with ratings, votes, genres, etc.
- `ipl-matches.csv` — 950 IPL matches with season, teams, toss info, etc.
- `batsman_runs_ipl.csv` — total IPL runs scored by every batter

### Setup — import pandas and load all three datasets

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv')
ipl = pd.read_csv('ipl-matches.csv')
bat = pd.read_csv('batsman_runs_ipl.csv')

print(movies.shape, ipl.shape, bat.shape)

(1629, 18) (950, 20) (605, 2)

---
## 1. GroupBy Basics

GroupBy splits your data into smaller groups based on a column, so you can study each group separately instead of the whole table at once.

**Real-life analogy:** Imagine 950 IPL matches all mixed together. Grouping by `Season` sorts every match into its own pile — a pile for 2019, a pile for 2020, and so on.

In [51]:
bat

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [52]:
ipl.head(10)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
9,1304111,Mumbai,2022-05-17,2022,65,Sunrisers Hyderabad,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Sunrisers Hyderabad,Runs,3.0,NaN,RA Tripathi,"['Abhishek Sharma', 'PK Garg', 'RA Tripathi', ...","['RG Sharma', 'Ishan Kishan', 'DR Sams', 'Tila...",CB Gaffaney,N Pandit

In [59]:
# Just grouping alone doesn't show a table yet — it creates a GroupBy object
a=ipl.groupby('Season').head(1)
a

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
194,1181768,Hyderabad,2019-05-12,2019,Final,Mumbai Indians,Chennai Super Kings,Rajiv Gandhi International Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",IJ Gould,Nitin Menon
254,1136620,Mumbai,2018-05-27,2018,Final,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,SR Watson,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",M Erasmus,S Ravi
314,1082650,Hyderabad,2017-05-21,2017,Final,Mumbai Indians,Rising Pune Supergiant,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,KH Pandya,"['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...","['AM Rahane', 'RA Tripathi', 'SPD Smith', 'MS ...",NJ Llong,S Ravi
373,981019,Bangalore,2016-05-29,2016,Final,Royal Challengers Bangalore,Sunrisers Hyderabad,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,8.0,NaN,BCJ Cutting,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...","['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...",HDPK Dharmasena,BNJ Oxenford
433,829823,Kolkata,2015-05-24,2015,Final,Mumbai Indians,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Mumbai Indians,Runs,41.0,NaN,RG Sharma,"['LMP Simmons', 'PA Patel', 'RG Sharma', 'KA P...","['DR Smith', 'MEK Hussey', 'SK Raina', 'MS Dho...",HDPK Dharmasena,RK Illingworth
492,734049,Bangalore,2014-06-01,2014,Final,Kolkata Knight Riders,Kings XI Punjab,M Chinnaswamy Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,3.0,NaN,MK Pandey,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'...",HDPK Dharmasena,BNJ Oxenford
552,598073,Kolkata,2013-05-26,2013,Final,Chennai Super Kings,Mumbai Indians,Eden Gardens,Mumbai Indians,bat,N,Mumbai Indians,Runs,23.0,NaN,KA Pollard,"['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...","['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar...",HDPK Dharmasena,SJA Taufel
628,548381,Chennai,2012-05-27,2012,Final,Kolkata Knight Riders,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,MS Bisla,"['MS Bisla', 'G Gambhir', 'JH Kallis', 'LR Shu...","['MEK Hussey', 'M Vijay', 'SK Raina', 'MS Dhon...",BF Bowden,SJA Taufel
702,501271,Chennai,2011-05-28,2011,Final,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,58.0,NaN,M Vijay,"['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...",Asad Rauf,SJA Taufel
775,419165,Mumbai,2010-04-25,2009/10,Final,Chennai Super Kings,Mumbai Indians,Dr DY Patil Sports Academy,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,22.0,NaN,SK Raina,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['S Dhawan', 'SR Tendulkar', 'AM Nayar', 'Harb...",RE Koertzen,SJA Taufel
835,392239,Johannesburg,2009-05-24,2009,Final,Royal Challengers Bangalore,Deccan Chargers,New Wanderers Stadium,Royal Challengers Bangalore,field,N,Deccan Chargers,Runs,6.0,NaN,A Kumble,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy...",RE Koertzen,SJA Taufel
892,336040,Mumbai,2008-06-01,2007/08,Final,Chennai Super Kings,Rajasthan Royals,Dr DY Patil Sports Academy,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...","['NK Patel', 'SA Asnodkar', 'Kamran Akmal', 'S...",BF Bowden,RE Koertzen

**Variation — look inside ONE specific group using `get_group()`:**

In [4]:
# get_group() lets you pull out just ONE group to inspect closely
ipl.groupby('Season').get_group('2022')[['City','Season','Team1','Team2','Venue','Player_of_Match','WinningTeam']].head()

,City,Season,Team1,Team2,Venue,Player_of_Match,WinningTeam
0,Ahmedabad,2022,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",HH Pandya,Gujarat Titans
1,Ahmedabad,2022,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",JC Buttler,Rajasthan Royals
2,Kolkata,2022,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",RM Patidar,Royal Challengers Bangalore
3,Kolkata,2022,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",DA Miller,Gujarat Titans
4,Mumbai,2022,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Harpreet Brar,Punjab Kings

**Variation — grouping the movies dataset instead of ipl:**

In [5]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [6]:
movies.groupby('year_of_release').head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512,Baaja,tt0405722,NaN,https://en.wikipedia.org/wiki/Baaja,Mouth Organ,Baaja,0,2001,\N,Family,6.6,8,NaN,Add a Plot »,NaN,Ram Awana|Saroj Bhagwar|Roni Bhatt|Chitra Pand...,NaN,NaN
1565,Kabhi Khushi Kabhie Gham...,tt0248126,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kabhi_Khushi_Kab...,Kabhi Khushi Kabhie Gham...,Kabhi Khushi Kabhie Gham...,0,2001,210,Drama|Musical|Romance,7.4,41143,Yashvardhan Raichand lives a very wealthy life...,After marrying a poor woman rich Rahul is dis...,Any weak man can say he's sorry. It takes a st...,Amitabh Bachchan|Jaya Bachchan|Shah Rukh Khan|...,24 wins & 43 nominations,14 December 2001 (USA)
1567,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1568,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1569,Gadar: Ek Prem Katha,tt0284137,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gadar:_Ek_Prem_K...,Gadar: Ek Prem Katha,Gadar: Ek Prem Katha,0,2001,170,Action|Drama|Romance,7.2,9372,Amongst the communal riots that erupt in the c...,Set during the Partition of India in 1947 a S...,A saga of love during the Indo-Pak partition.,Sunny Deol|Ameesha Patel|Amrish Puri|Lillete D...,7 wins & 33 nominations,15 June 2001 (India)

---
## 2. Aggregate Functions on Groups

Once grouped, we can run maths functions on each group: `sum()`, `mean()`, `count()`, `max()`, `min()`.

In [7]:
movies.head(10)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,0,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,NaN,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,NaN,25 January 2019 (India)

In [8]:
# mean() -> average rating per year
movies.groupby('year_of_release')['imdb_rating'].mean().head(8)

year_of_release
2001    5.636066
2002    5.142105
2003    5.518182
2004    5.251899
2005    5.356701
2006    5.375294
2007    5.600000
2008    5.208219
Name: imdb_rating, dtype: float64

In [9]:
# sum() -> total votes received per year, across all movies
movies.groupby('year_of_release')['imdb_votes'].sum().head(8)

year_of_release
2001    387727
2002    154115
2003    302048
2004    327421
2005    233650
2006    450114
2007    551140
2008    315559
Name: imdb_votes, dtype: int64

In [10]:
movies.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [11]:
# count() -> how many movies released each year
movies.groupby('year_of_release')['title_x'].count().head(8)

year_of_release
2001    61
2002    76
2003    99
2004    79
2005    97
2006    85
2007    84
2008    73
Name: title_x, dtype: int64

In [12]:
# max() and min() -> highest and lowest rating per year
print(movies.groupby('year_of_release')['imdb_rating'].max().head(5))
print()
print(movies.groupby('year_of_release')['imdb_rating'].min().tail(5))

year_of_release
2001    8.1
2002    8.3
2003    8.2
2004    8.7
2005    8.2
Name: imdb_rating, dtype: float64

year_of_release
2015    0.0
2016    0.0
2017    0.0
2018    1.7
2019    0.0
Name: imdb_rating, dtype: float64

**Variation — same idea, but on the IPL dataset (matches won per team):**

In [13]:
# size() here works like value_counts() -> total matches won by each team
ipl.groupby('WinningTeam').size().sort_values(ascending=False).head(8)

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Kings XI Punjab                 88
Sunrisers Hyderabad             75
Delhi Daredevils                67
dtype: int64

**Variation — average runtime of movies per year (runtime needs converting to numbers first):**

In [14]:
movies['runtime'] = pd.to_numeric(movies['runtime'], errors='coerce')
movies.groupby('year_of_release')['runtime'].mean().head(8)

year_of_release
2001    156.000000
2002    150.359375
2003    138.791209
2004    145.882353
2005    136.186813
2006    138.807692
2007    130.000000
2008    133.838710
Name: runtime, dtype: float64

---
## 3. size() vs count() — What's the Real Difference?

`count()` skips missing (NaN) values. `size()` counts every row in the group, no matter what. Let's prove it using the IPL dataset's `City` column, which has real missing values.

In [15]:
ipl['City'].isnull().sum()

np.int64(51)

In [16]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [17]:
# Compare count() and size() on the same column, same groups
comparison = pd.DataFrame({
    'count()': ipl.groupby('Season')['City'].count(),
    'size()': ipl.groupby('Season')['City'].size()
})
comparison[comparison['count()'] != comparison['size()']]

         count()  size()
Season
2014          47      60
2020/21       22      60

---
## 4. Single vs Multiple Column Aggregation — `agg()`

`agg()` lets you run several calculations at once, instead of writing separate lines for each one.

In [18]:
# a) Multiple aggregations on ONE column -> pass a list
movies.groupby('year_of_release')['imdb_rating'].agg(['mean', 'sum', 'count','max','min']).head(5)

                     mean    sum  count  max  min
year_of_release
2001             5.636066  343.8     61  8.1  3.0
2002             5.142105  390.8     76  8.3  2.8
2003             5.518182  546.3     99  8.2  2.1
2004             5.251899  414.9     79  8.7  2.3
2005             5.356701  519.6     97  8.2  2.5

In [19]:
# b) Different aggregations on DIFFERENT columns -> pass a dictionary
movies.groupby('year_of_release').agg({'imdb_rating': 'mean', 'imdb_votes': 'sum'}).head(6)

                 imdb_rating  imdb_votes
year_of_release
2001                5.636066      387727
2002                5.142105      154115
2003                5.518182      302048
2004                5.251899      327421
2005                5.356701      233650
2006                5.375294      450114

**Variation — agg() on the IPL dataset: number of matches AND number of unique winning teams, per season:**

In [20]:
ipl.groupby('Season').agg({'ID': 'count', 'WinningTeam': 'nunique'}).head(8)

         ID  WinningTeam
Season
2007/08  58            8
2009     57            8
2009/10  60            8
2011     73           10
2012     74            9
2013     76            9
2014     60            8
2015     59            8

**Variation — agg() with a custom function using a lambda (range of ratings per year):**

In [21]:
movies.groupby('year_of_release')['imdb_rating'].agg(lambda x: x.max() - x.min()).head(8)

year_of_release
2001    5.1
2002    5.5
2003    6.1
2004    6.4
2005    5.7
2006    6.1
2007    6.7
2008    6.3
Name: imdb_rating, dtype: float64

---
## 5. Grouping by Multiple Columns

Pass a LIST of column names to split by more than one column at once — each extra column adds another level of grouping.

In [22]:
ipl.groupby(['Season', 'TossDecision'])['ID']

In [23]:
# Group by Season AND TossDecision together
ipl.groupby(['Season', 'TossDecision'])['ID'].count().head(10)

Season   TossDecision
2007/08  bat             26
         field           32
2009     bat             35
         field           22
2009/10  bat             39
         field           21
2011     bat             25
         field           48
2012     bat             37
         field           37
Name: ID, dtype: int64

**Variation — group by Season AND WinningTeam (which team won most, in which season):**

In [24]:
season_team_wins = ipl.groupby(['Season', 'WinningTeam'])['ID'].count()
season_team_wins.sort_values(ascending=False).head(10)

Season   WinningTeam
2007/08  Rajasthan Royals         13
2013     Mumbai Indians           13
2012     Kolkata Knight Riders    12
2014     Kings XI Punjab          12
2013     Chennai Super Kings      12
2017     Mumbai Indians           12
2022     Gujarat Titans           12
2012     Delhi Daredevils         11
2011     Chennai Super Kings      11
2013     Rajasthan Royals         11
Name: ID, dtype: int64

**Variation — group by three columns at once (City, TossDecision, SuperOver):**

In [25]:
ipl.groupby(['City', 'TossDecision', 'SuperOver'])['ID'].count().head(10)

City       TossDecision  SuperOver
Abu Dhabi  bat           N            17
                         Y             1
           field         N            18
                         Y             1
Ahmedabad  bat           N             7
           field         N            11
                         Y             1
Bangalore  bat           N             8
           field         N            54
                         Y             1
Name: ID, dtype: int64

**Bonus — `value_counts()` is basically a shortcut for `groupby(col).size()`, sorted automatically:**

In [26]:
ipl['WinningTeam'].value_counts().head(5)

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Name: count, dtype: int64

---
## 6. pd.concat() — Stacking DataFrames Together

Use `concat()` when your data is split across multiple DataFrames and you just want to STACK them — as more rows, or as more columns.

In [27]:
# a) Stacking ROWS together -> axis=0 (default)
batch1 = bat.iloc[0:3]      # pretend this came from File 1
batch2 = bat.iloc[3:6]      # pretend this came from File 2

pd.concat([batch1, batch2])

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25
5     A Dananjaya            4

In [28]:
# Understanding Ignore Index Parameter
import pandas as pd

batch1 = pd.DataFrame({
    "Name": ["Amit", "Rahul"]    
})

batch2 = pd.DataFrame({
    "Name": ["Priya", "Sneha"]
})

pd.concat([batch1, batch2],ignore_index=True)

    Name
0   Amit
1  Rahul
2  Priya
3  Sneha

In [29]:
# Fixing the index so it doesn't repeat
pd.concat([batch1, batch2], ignore_index=True)

    Name
0   Amit
1  Rahul
2  Priya
3  Sneha

**Variation — using the `keys=` parameter to remember WHICH batch each row came from:**

In [30]:
combined = pd.concat([batch1, batch2], keys=['File1', 'File2'])
combined

          Name
File1 0   Amit
      1  Rahul
File2 0  Priya
      1  Sneha

In [31]:
# b) Joining COLUMNS together, side by side -> axis=1
top5 = bat.sort_values('batsman_run', ascending=False).head(5).reset_index(drop=True)
strike_rate = pd.DataFrame({'strike_rate': [139.8, 128.4, 143.9, 130.5, 136.7]})

pd.concat([top5, strike_rate], axis=1)

      batter  batsman_run  strike_rate
0    V Kohli         6634        139.8
1   S Dhawan         6244        128.4
2  DA Warner         5883        143.9
3  RG Sharma         5881        130.5
4   SK Raina         5536        136.7

---
## 7. pd.merge() — Joining DataFrames Using a Common Column

`merge()` matches rows between two DataFrames using a COMMON column, like a SQL join. Let's build two small tables that DON'T perfectly match, so we can clearly see how each join type behaves.

In [32]:
top_batsmen = bat.sort_values('batsman_run', ascending=False).head(5).reset_index(drop=True)
print(top_batsmen)

player_team = pd.DataFrame({
    'batter': ['V Kohli', 'S Dhawan', 'DA Warner', 'RG Sharma', 'MS Dhoni'],
    'Team': ['RCB', 'DC', 'SRH', 'MI', 'CSK']
})
print(player_team)

      batter  batsman_run
0    V Kohli         6634
1   S Dhawan         6244
2  DA Warner         5883
3  RG Sharma         5881
4   SK Raina         5536
      batter Team
0    V Kohli  RCB
1   S Dhawan   DC
2  DA Warner  SRH
3  RG Sharma   MI
4   MS Dhoni  CSK

In [33]:
# a) how='inner' (default) -> keep only rows that match in BOTH tables
pd.merge(top_batsmen, player_team, on='batter', how='inner')

      batter  batsman_run Team
0    V Kohli         6634  RCB
1   S Dhawan         6244   DC
2  DA Warner         5883  SRH
3  RG Sharma         5881   MI

In [34]:
# b) how='left' -> keep every row from the LEFT table
pd.merge(top_batsmen, player_team, on='batter', how='left')

      batter  batsman_run Team
0    V Kohli         6634  RCB
1   S Dhawan         6244   DC
2  DA Warner         5883  SRH
3  RG Sharma         5881   MI
4   SK Raina         5536  NaN

In [35]:
# c) how='right' -> keep every row from the RIGHT table
pd.merge(top_batsmen, player_team, on='batter', how='right')

      batter  batsman_run Team
0    V Kohli       6634.0  RCB
1   S Dhawan       6244.0   DC
2  DA Warner       5883.0  SRH
3  RG Sharma       5881.0   MI
4   MS Dhoni          NaN  CSK

In [36]:
# d) how='outer' -> keep every row from BOTH tables
pd.merge(top_batsmen, player_team, on='batter', how='outer')

      batter  batsman_run Team
0  DA Warner       5883.0  SRH
1   MS Dhoni          NaN  CSK
2  RG Sharma       5881.0   MI
3   S Dhawan       6244.0   DC
4   SK Raina       5536.0  NaN
5    V Kohli       6634.0  RCB

**Variation — using `left_on` / `right_on` when the shared column has a different name:**

In [37]:
player_team_v2 = player_team.rename(columns={'batter': 'PlayerName'})

pd.merge(top_batsmen, player_team_v2, left_on='batter', right_on='PlayerName', how='inner')

      batter  batsman_run PlayerName Team
0    V Kohli         6634    V Kohli  RCB
1   S Dhawan         6244   S Dhawan   DC
2  DA Warner         5883  DA Warner  SRH
3  RG Sharma         5881  RG Sharma   MI

**Variation — using `suffixes` when both tables share a column name that ISN'T the join key:**

In [38]:
season1 = pd.DataFrame({'batter': ['V Kohli', 'S Dhawan'], 'runs': [973, 689]})
season2 = pd.DataFrame({'batter': ['V Kohli', 'S Dhawan'], 'runs': [741, 502]})

pd.merge(season1, season2, on='batter', suffixes=('_2023', '_2024'))

     batter  runs_2023  runs_2024
0   V Kohli        973        741
1  S Dhawan        689        502

---
## 🎯 Quick Recap

| Concept | What it does |
|---|---|
| `groupby('col')` | Splits data into groups based on a column's values |
| `sum()/mean()/count()/max()/min()` | Aggregate calculations applied to each group |
| `size()` vs `count()` | `size()` counts ALL rows; `count()` skips missing values |
| `agg([...])` / `agg({...})` | Multiple calculations at once — one column, or different ones per column |
| `groupby(['col1','col2'])` | Groups by more than one column |
| `pd.concat()` | Stacks DataFrames — more rows (axis=0) or more columns (axis=1) |
| `pd.merge()` | Joins two DataFrames using a shared column (inner/left/right/outer) |

---
## 🏠 Homework Practice — try these yourself below

1. Group the IPL dataset by `Team1` and count how many matches each team played as Team1.
2. On movies, group by `year_of_release` and find BOTH min and max `imdb_rating` using `agg()`.
3. Group `ipl` by `['Season', 'Venue']` and find which venue hosted the most matches each season.
4. Split any dataset into two halves and combine them back using `pd.concat()`.
5. Create two small DataFrames with one mismatched row each, then try all 4 merge types and compare.

In [39]:
# 1. Your code here

In [40]:
# 2. Your code here

In [41]:
# 3. Your code here

In [42]:
# 4. Your code here

In [43]:
# 5. Your code here